-- Made with MS SQL
SELECT SUM(P.AMOUNT * ISNULL(CR.EXCHANGE_RATE_TO_EUR, 1))
           AS AMOUNT_EUR,
       P.TRANSACTION_DATE
FROM PAYMENTS P
         JOIN CURRENCIES C ON P.CURRENCY = C.CURRENCY_ID
         LEFT JOIN CURRENCY_RATES CR ON P.CURRENCY = CR.CURRENCY_ID
    AND P.TRANSACTION_DATE = CR.EXCHANGE_DATE
         LEFT JOIN BLACKLIST B ON P.USER_ID_SENDER = B.USER_ID
WHERE B.USER_ID IS NULL
  AND C.END_DATE IS NULL
GROUP BY P.TRANSACTION_DATE;